name: hello world1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses:_actions/checkout@v2
      - name: hello world
        run: echo "hello World"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: _echo "Goodbye- world"
        shell: bash
