name: hello world1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: hello world
        uses: actions/checkout@v4
        run:  echo "hello world"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run |
          echo "Goodbye- world"
        shell: bash
